# Generated by Django 5.0.7 on 2024-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='city',
            field=models.CharField(default='Bern', max_length=64),
            preserve_default=False,
        ),
    ]
