# Generated by Django 5.0.7 on 2024-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_show_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='address',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
